version: '3'

volumes:
  express_node_modules:
  postgres_db:

services:
  express:
    build:
      context: .
      dockerfile: ./compose/express/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - db
    ports:
      - "3006:3006"
    volumes:
      - .:/app/
      - express_node_modules:/app/node_modules
  db:
    image: postgres:10.3
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_DB:postgres
